### ISSUE TITLE
Profiles [issue #2]

### ISSUE THREAD

**Issue by Arinerron** [calagator/calagator.org#20]
This is a feature request. It will require a lot of work, but I think the outcome will be worth it.

Essentially, I suggest you add profiles and accounts, and allow people to connect with eachother. Another part of the feature would be to mark events in some way saying you're going so you can keep in contact with people afterwards.

Thanks!

**Comment by aeschright** [comment]
Thanks for the suggestion! Since this has been sitting since 2016, I think it's fair to say that we aren't going to be able to consider it in a timely fashion. In the past, we've considered this sort of feature out of scope with our intentions, so I'm closing the ticket -- but I'm open to hearing about more decentralized approaches for integrating with personal calendars and networks.
